"""new_migratio2

Revision ID: 3d1c0c2e35fa
Revises: 71d8e7a769cd
Create Date: 2024-06-09 14:29:19.667577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1c0c2e35fa'
down_revision: Union[str, None] = '71d8e7a769cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_list', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint('todo_list_user_id_fkey', 'todo_list', type_='foreignkey')
    op.create_foreign_key(None, 'todo_list', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_list', type_='foreignkey')
    op.create_foreign_key('todo_list_user_id_fkey', 'todo_list', 'user', ['user_id'], ['id'])
    op.alter_column('todo_list', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
